FROM node:10.18.1-alpine3.10
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
RUN apk update && apk add nginx && mkdir -p /run/nginx

COPY /dist /var/lib/nginx/html
COPY ./default.conf /etc/nginx/conf.d/default.conf

WORKDIR /etc/init.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
